version: '3.8'

services:
  postgres:
    image: postgres:15.0-alpine
    ports:
      - "4445:5432"
    volumes:
      - data:/var/lib/postgresql1/data
    environment:
      POSTGRES_DB: whatsai
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user

  whatsai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${PORT}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - BASEURL=${BASEURL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}
      

volumes:
  data:
